alpacahq/alpaca-trade-api-go

- Gopkg.lock
- Gopkg.toml
- alpaca/alpaca_test.go
- alpaca/entities.go
- alpaca/rest.go
- alpaca/stream.go
- polygon/rest.go
- polygon/stream.go
- stream/stream.go
- stream/stream_test.go
also unified streaming interface. this is going to need some love, and extensive testing, but I will address that as I build a sample algo.
> alpaca rest & streaming API support

- alpaca/alpaca_test.go
- alpaca/rest.go
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
> Gofmt files

- alpaca/entities.go
- alpaca/rest.go
It seems there is missing `base` URL for `GetPosition` for rest client
> Fix broken URL parsing for GetPosition

- README.md
- alpaca/rest.go
Per issues #4 and #13, better in-code configuration of the URL is desired.
> Add SetBaseUrl method

- alpaca/alpaca_test.go
- alpaca/entities.go
- alpaca/rest.go
This update addresses issues with the handling of the current format of data from Alpaca's `/bars` endpoint.
> Update handling of response from bars endpoint

- alpaca/entities.go
> Added missing Order Entity value "filled_avg_price"

- alpaca/entities.go
Was trying to log partially filled orders and noticed the missing field. Didn't find any guidelines for contributing so I just tried to follow the general coding pattern in the file. Hope this helps!
> Added missing "FilledQty" field to Order struct.

- Gopkg.toml
- README.md
- polygon/stream.go
> Update Nats url

- polygon/entities.go
- polygon/polygon_test.go
- polygon/rest.go
> Add optional params for GetHistoricTrades

- examples/mean-reversion.go
Adds mean-reversion trading algorithm to golang SDK
> Add mean reversion example

- alpaca/rest.go
https://docs.alpaca.markets/api-documentation/api-v2/orders/#cancel-all-orders
> Add endpoint to cancel all open orders

- alpaca/stream.go
- polygon/stream.go
Addressing the concerns in issue #48 regarding reconnection not re-subscribing to channels.
> Implement re-subscription on websocket reconnection

- alpaca/alpaca_test.go
- alpaca/entities.go
- alpaca/rest.go
- examples/long-short/long-short.go
- examples/mean-reversion/mean-reversion.go
This adds handling for the planned implementation of multi-leg order options.
> Add support for advanced order types

- alpaca/entities.go
- alpaca/rest.go
see https://alpaca.markets/docs/api-documentation/api-v2/assets/#asset-entity
> misc updates to outdated methods and fields

- alpaca/entities.go
we change the trade id to string
> Data stream trade id is now a string

- alpaca/entities.go
- alpaca/rest.go
Fixed spelling error in AccountActivity type.
Fixes #84
> Bugfix for typo in "AccountActvity"

- examples/martingale/martingale.go
Part of article on converting strategies from Python to Go.
I'll update the README once the article is published
> Add martingale example

- alpaca/entities.go
@shlomikushchi could you please review?
Related to #105
> Add ReplacedBy to Orders struct

- alpaca/alpaca_test.go
- alpaca/entities.go
- alpaca/rest.go
- examples/long-short/long-short.go
- examples/martingale/martingale.go
- examples/mean-reversion/mean-reversion.go
NOTE: This is for the v2 branch!
> Refactor notional order API

- marketdata/stream/client.go
- marketdata/stream/client_test.go
- marketdata/stream/entities.go
- marketdata/stream/flow.go
- marketdata/stream/flow_test.go
- marketdata/stream/message.go
- marketdata/stream/message_test.go
- marketdata/stream/options.go
- marketdata/stream/options_test.go
- marketdata/stream/subscription.go
- marketdata/stream/subscription_test.go
Please merge this to `v2` after #135  has been merged (after rebasing this PR to that branch)
> Add LULD to StocksClient

- examples/crypto-stream/crypto_stream.go
- marketdata/stream/client_test.go
- marketdata/stream/entities.go
- marketdata/stream/message.go
- marketdata/stream/message_test.go
New fields:
Crypto trade: id, taker side
Crypto quote: bid size, ask size
> Add some fields to crypto trades and quotes

- alpaca/alpaca_test.go
- alpaca/entities.go
fixes issue https://github.com/alpacahq/alpaca-trade-api-go/issues/110
> fixed json tag on asset entity

- CODEOWNERS
Please feel free to extend. But also tagging @gnvk, not sure if you want to be in this for auto tagging on PRs and such.
> Adds a CODEOWNERS file

- alpaca/stream.go
> Add OAuth support for trade updates

- examples/crypto-stream/crypto_stream.go
- marketdata/stream/client.go
- marketdata/stream/client_test.go
- marketdata/stream/entities.go
- marketdata/stream/flow.go
- marketdata/stream/message.go
- marketdata/stream/message_test.go
- marketdata/stream/options.go
- marketdata/stream/subscription.go
Support streaming crypto orderbook
> Crypto orderbook

- marketdata/stream/client.go
I found a minor typo in doc and wanted to fix. I understand if you don't want to merge.
> StreamClientDocTypoFix: minor update to StreamClient doc fixing typo

- alpaca/rest.go
- alpaca/rest_test.go
- examples/mean-reversion/mean-reversion.go
> Return order(s) from the close position methods

- go.mod
- go.sum
Fixes https://github.com/alpacahq/alpaca-trade-api-go/issues/251.
> Remove replace directive from go.mod

- alpaca/trading.go
- alpaca/trading_test.go
- examples/martingale/martingale.go
- examples/mean-reversion/mean-reversion.go
> Round limit-price to avoid sub-penny issue

- .gitignore
- examples/mean-reversion/mean-reversion.go
> Stop trading after the final daily liquidation

- README.md
- alpaca/rest.go
- alpaca/rest_test.go
- marketdata/rest.go
> Add support for broker authentication

- marketdata/rest_test.go
- marketdata/stream/client_test.go
This PR include written tests to cover the crypto perpetual market data functionality. Tests cover both ws stream and REST.
> Tests for crypto perpetual market data

- marketdata/rest.go
- marketdata/rest_test.go
> Use the v1 endpoint for corporate actions

- .golangci.yml
- alpaca/entities.go
- alpaca/entities_easyjson.go
- alpaca/rest.go
- alpaca/rest_test.go
- examples/bull-spread/bull-spread.go
Adding support for multi-leg complex option strategies.
> Support multi-leg orders for complex option strategies
