- polygon/entities.go
This PR adds the Stocks Aggregate streaming entity, as defined in https://polygon.io/sockets.
> Add streaming entities

- polygon/entities.go
- polygon/polygon_test.go
- polygon/rest.go
I added the ability for a client to request the /exchanges REST endpoint. This lets a client decode the 'Exchange' field in TradeStream messages to a human readable exchange name.
> polygon.io /exchanges endpoint

- alpaca/alpaca_test.go
- alpaca/rest.go
This adds the [get order](https://docs.alpaca.markets/api-documentation/web-api/orders/#get-an-order) API to the client.
Although [`get-an-order-by-client-order-id`](https://docs.alpaca.markets/api-documentation/web-api/orders/#get-an-order-by-client-order-id) exists, I was largely copying the existing `cancel-order` endpoint, which uses `orderID string`.
> Add GetOrder endpoint

- alpaca/alpaca_test.go
- alpaca/rest.go
As issue #19 points out, quotes have been removed from Alpaca's data API. This removes them from the SDK.
> Remove deprecated Quotes data endpoints

- polygon/entities.go
- polygon/rest.go
This change adds the new Polygon v2 aggregate method, which is reportedly more stable than its v1 counterpart. It also changes the type of the `volume` field in AggTick from int to float, as calls for AAPL aggregates were failing on day-length timeframes.
> Add v2 aggregates to Polygon REST API

- alpaca/rest.go
This update changes the version of the Alpaca trade API used from v1 to v2 by default. The old v1 functionality can be accessed by setting the `APCA_API_VERSION` environment variable to `v1`.
> Change default trade API version to v2

- alpaca/rest.go
There are a couple issues with the method, namely that it adds an extraneous `/` character to the data URL and that it does not handle missing timeframes in a very clear way. This corrects these issues.
> Fix issues with bar data retrieval

- alpaca/rest.go
Specify the client when calling ListBars in GetSymbolBars to prevent fallback to the default client, which may cause unpredictable behavior/errors
> Specify client in GetSymbolBars

- README.md
- polygon/entities.go
- polygon/stream.go
Polygon's NATS socket is going to be deprecated at some point, so we're switching the stream connection used by the SDK to use Websockets instead. Necessary code changes should be minimal; you can see in the readme a new way to access the data objects in your handler methods.
> Switch Polygon streaming from NATS to Websocket

- alpaca/rest.go
- common/credentials.go
Alpaca will be adding support for OAuth authentication on a limited basis in the future. This adds the ability to configure an OAuth token via environment variable.
> Add alternative authentication via OAuth

- alpaca/rest.go
As far as I can see, this has no bearing on the code, and instead prints out blank spaces.
> Remove excess print

- polygon/entities.go
The [trade stream on Polygon](https://polygon.io/sockets) now provides a trade ID:
> Add trade ID to streams

- go.mod
- polygon/entities.go
Addresses issue #66 
Currently when using the sdk i see errors like
`2020/04/16 19:55:07 polygon stream read error (json: cannot unmarshal string into Go struct field StreamTrade.i of type int64)`
This can be solved by changing the type to string.
> Change trade id to be string

- common/credentials.go
- polygon/rest.go
- polygon/stream.go
A paper Alpaca API key no longer works for Polygon. From Quintin Pike, in Slack's #dev-polygon:
> We have upgraded WebSockets to the latest version which has proven much more stable. In doing that the auth service has been rewritten. Apparently, before you could use paper trading credentials. However, that was unintentional and fixed in the new service.
This poses a bit of a problem. I want to consume Polygon data, but I want to keep using my paper account.
The only solution I can think around this is to have the Polygon API key be a separate env var. This can be a prod Alpaca key, while the Alpaca client can continue to use the paper API keys.
/cc @ttt733 @umitanuki
> Establish a separate Polygon API key

- alpaca/rest.go
this is needed since we removed trailing slash from the default data url
> add a single forward slash to ListBars url format

- polygon/stream.go
polygon websokcet changed for alpaca users to socket.polygon.io
it used to be alpaca.socket.polygon.io
> Changed polygon ws to socket.polygon.io

- alpaca/entities.go
oto and oco weren't defined in entities.go
> Adding oto, oco to OrderClass

- README.md
- alpaca/stream.go
There's a way to execute more than one algorithm at once.<br>
The websocket connection is limited to 1 connection per account. <br>
For that exact purpose this ![project](https://github.com/shlomikushchi/alpaca-proxy-agent)  
was created<br>
This PR enable the usage of the proxy
> Add support for the alpaca-proxy-agent

- alpaca/rest.go
Fix the wrong query param names according to https://alpaca.markets/docs/api-documentation/api-v2/market-data/bars/.
> fix start and end params for rest endpoint

- alpaca/stream.go
- polygon/stream.go
- stream/stream.go
- stream/stream_test.go
With this PR I added the functionality to unsubscribe specific streaming channels.
Example:
```
// Subscribe to channel
err = stream.Register("T.*", handler)
// Unsubscribe channel
err = stream.Deregister("T.*")
```
This functionality is already possible in the python version of this package.
> feat(unsubscribe): added unsubscribe functionality to stream

- alpaca/entities.go
As far as I can tell, this is all that's missing to place extended_hours requests via the Go SDK. If I'm missing something, please let me know. :)
> Add ExtendedHours into PlaceOrderRequest

- examples/mean-reversion/mean-reversion.go
Fixes a small bug in the mean-reversion example where we mean to sell our shares instead of buy them.
> Fix mean-reversion example

- alpaca/entities.go
When trade updates are sent over the websocket, they sometimes (depending on the event) include `position_qty`, `price`, `qty`, `timestamp`, and `execution_id`. These are particularly useful for `partial_fill` updates where you need to know how many shares were filled as part of the partial fill.
Pulled from the docs here:
https://alpaca.markets/docs/api-documentation/api-v2/streaming/
Here's a sample `fill` event that contains these items:
```json
{
"stream": "trade_updates",
"data": {
"event": "fill",
"execution_id": "adb4f7c7-45fe-4a3a-a0ac-02d9fa3c8264",
"order": {
"asset_class": "us_equity",
"asset_id": "3e59f0bd-a197-4e69-995a-733be53ecb0f",
"canceled_at": null,
"client_order_id": "2bc205b7-57d4-4aee-8cd4-129f51b152fd",
"created_at": "2021-07-29T15:28:16.830808Z",
"expired_at": …
```
> Add timestamp, position_qty, qty, price to TradeUpdate websocket struct

- alpaca/alpaca_test.go
- alpaca/entities.go
Related to [issue](https://github.com/alpacahq/alpaca-trade-api-go/issues/112). Updated tests.
> updating volume entity to return int64 for volume.

- marketdata/stream/client.go
- marketdata/stream/client_test.go
- marketdata/stream/entities.go
- marketdata/stream/errors.go
- marketdata/stream/flow.go
- marketdata/stream/flow_test.go
- marketdata/stream/message.go
- marketdata/stream/subscription.go
Big fix: 
- certain errors were not logged with an established connection (important one being 407: slow client)
Small fix:
- handle insufficient scope as irrecoverable
> Improve marketdata stream error handling for a few cases

- marketdata/entities.go
- marketdata/rest.go
- marketdata/rest_test.go
Add method to query crypto snapshot endpoint.
- ~Add unit test~
```
css, err := marketdata.GetCryptoSnapshot("ETHUSD", "CBSE")
(dlv) p css 
*github.com/alpacahq/alpaca-trade-api-go/v2/marketdata.CryptoSnapshot {                                                                                                                                    
LatestTrade: *github.com/alpacahq/alpaca-trade-api-go/v2/marketdata.CryptoTrade {                                                                                                                  
Timestamp: (*time.Time)(0xc000382730),                                                                                                                                                     
Price: 4393.18, …
```
> Added GetCryptoSnapshot()

- go.mod
- go.sum
- marketdata/stream/client.go
- marketdata/stream/client_test.go
- marketdata/stream/options.go
- marketdata/stream/options_test.go
Allows the market data streaming client to supply a callback function as an option to run on connect/disconnect from the stream. The primary use case is for supporting monitoring and alerting workflows (e.g. prometheus metrics).
> Add (dis)connect callbacks to market data stream client

- alpaca/rest.go
- alpaca/rest_test.go
Currently the function is using .String() for date fields which is a invalid date format of `2006-01-02 15:04:05.999999999 -0700 MST` for the API. I updated the fields to explicitly use RFC3339 which is a perfectly valid format. Tested using go1.19.1.
> Fixed invalid date formats for GetAccountActivities

- alpaca/entities.go
- alpaca/rest.go
- alpaca/rest_test.go
According to the [API Doc](https://alpaca.markets/docs/api-references/trading-api/orders/#get-a-list-of-orders), there is a query parameter for `side` in the list orders endpoint.
This PR adds the field to the according entity.
> Add side field to ListOrdersRequest

- alpaca/entities.go
- alpaca/rest.go
- alpaca/rest_test.go
Alpaca Documentation - https://alpaca.markets/docs/api-references/trading-api/watchlist/
Endpoints Added:
- GET - `/v2/watchlists` - Get all watchlists
- GET - `/v2/watchlists/{watchlist_id}` - Get a watchlist by id
- POST - `/v2/watchlists` - Create Watchlist
- POST - `/v2/watchlists/{watchlist_id}` - Add asset to watchlist
- PUT - `/v2/watchlists/{watchlist_id}` - Update watchlist by id
- DELETE - `/v2/watchlists/{watchlist_id}` - Delete a watchlist by id
- DELETE - `/v2/watchlists/{watchlist_id}/{symbol}` - Remove a symbol from watchlist
> feat: add watchlist endpoint implementation

- .github/workflows/go.yml
- alpaca/rest.go
- alpaca/version.go
- marketdata/rest.go
- marketdata/stream/conn_nhoory.go
- Adding User-Agent header on HTTP requests and WSS
- Similar to [alpaca-py](https://github.com/alpacahq/alpaca-py/blob/695f23de44c5410849b88acb77bdad09c327fb9f/alpaca/common/websocket.py#L78)
> Add User-Agent header on HTTP requests and WSS

- marketdata/stream/client_test.go
- marketdata/stream/subscription.go
Context:
- putting a request message into `c.subChanges` blocks process with having `c.pendingSubChangeMutex.Lock()` when subscribe request is called twice during disconnection
- this leads deadlock to wait `c.pendingSubChangeMutex.Lock()` in `connWriter()` when reconnecting
Changes:
- drain `c.subChanges` channel when timeout happens. expecting this happens only when disconnected as c.subChanges are consumed before the timeout by `connWriter()` if connected.
> fix: Remove sub changes request when timeout happens

- alpaca/entities.go
- alpaca/entities_easyjson.go
This is technically a backward incompatible change, however, since the struct was never used anywhere within the SDK and users found it [confusing](https://github.com/alpacahq/alpaca-trade-api-go/issues/275), we decided not to consider it a backward incompatible change.
Fixes #275
> Remove unused Fundamental struct

- alpaca/entities.go
- alpaca/entities_easyjson.go
- alpaca/rest.go
- alpaca/rest_test.go
> Liquidate all positions response format

- alpaca/entities.go
- alpaca/entities_easyjson.go
- alpaca/rest.go
- alpaca/rest_test.go
GetAccountActivitiesRequest:
- PageToken
- Category
AccountActivity:
- OrderID and OrderStatus (for FILL activities only) [are documented](https://docs.alpaca.markets/reference/getaccountactivities-2)
- Status (for non-FILL activities) is not documented
> Add missing AccountActivity and GetAccountActivitiesRequest fields

- alpaca/entities.go
- alpaca/rest.go
Resolves #289 
- PlaceOrderRequest is missing position_intent query param
> Add position intent to PlaceOrderRequest

- marketdata/stream/client.go
- marketdata/stream/client_test.go
- marketdata/stream/conn_test.go
- marketdata/stream/options.go
Slow client related issues:
* `client.maintainConnection` waits for the `messageProcessor` goroutine(s) to finish to reconnect: this delays the reconnect and more messages can be missed
* whenever the client buffer `c.in` is full the `connReader` goroutine is blocked: the TCP stack of the operating system will buffer the messages and can cause disconnects if the application gets the pong message late, moreover the `connReader` goroutine will not exit if the context is cancelled while it is blocked on writing to `c.in`
> Add logging and optional callback to buffer fills

- marketdata/stream/client.go
- marketdata/stream/client_test.go
- marketdata/stream/entities.go
- marketdata/stream/entities_easyjson.go
- marketdata/stream/flow.go
- marketdata/stream/flow_test.go
- marketdata/stream/message.go
- marketdata/stream/message_test.go
- marketdata/stream/options.go
- marketdata/stream/options_test.go
- marketdata/stream/subscription.go
- marketdata/stream/subscription_test.go
Imbalance messages are sent during Limit-up Limit-down trading halts on the stock market.
> Add order imbalance stock messages

- alpaca/rest.go
- alpaca/rest_test.go
The field `PositionIntent` was introduced in https://github.com/alpacahq/alpaca-trade-api-go/pull/294 as mandatory field, should've been optional 
Fixes https://github.com/alpacahq/alpaca-trade-api-go/issues/327
> Make PositionIntent optional in PlaceOrderRequest

- marketdata/stream/client.go
Ran the test on my local machine Apple M3 Pro, 36 GB Ram 
The string-based approach (is_http_4xx_string) is significantly faster than the regex-based approach (is_http_4xx_regex).
•	Regex approach: ~0.1275 seconds (for 100,000 executions)
•	String matching approach: ~0.0334 seconds (for 100,000 executions)
The string-matching method is about 3.8x faster than the regex approach.
> Replace regex with strings.Contains in isHTTP4xx

- alpaca/stream.go
Ran `alpaca/stream_test.go` and all tests were passed.
> Replace deprecated Dial with DialContext in http.Transport

- examples/marketdata/marketdata.go
The marketdata trades example queries the trades endpoint 2 times. The first query is exhaustive and does not return in time, so for demonstration purposes, we only keep the second.
> Fix marketdata trades example
